env:
  browser: true
  es6: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
ignorePatterns:
  - "node_modules/"
  - "functions/"
  - "build/"
plugins:
  - react
rules:
  keyword-spacing: 2 # [2, { "before": true, "after": true, "overrides": null }]
  comma-dangle: [2, "always-multiline"]
  indent: ["error", 2, { "SwitchCase": 1 }]
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  yoda: [error, never, { exceptRange: true }]
  valid-jsdoc:
    - 2
    -
      prefer:
        returns: "return"
        exception: "throws"
        property: "prop"
        arg: "param"
        argument: "param"
        func: "function"
        fires: "emits"
        overview: "file"
        fileoverview: "file"
        host: "external"
        description: "desc"
        defaultvalue: "default"
        constant: "const"
        augments: "extends"
        virtual: "abstract"
  valid-typeof: 2
  dot-location: [2, "property"]
  dot-notation: 0
  eqeqeq: [2, "allow-null"]
  no-alert: 2
  no-else-return: 2
  no-undef: 2
  brace-style: [2, "1tbs"]
  block-spacing: [2, "always"]
  array-bracket-spacing: [2, "never"]
  camelcase: [2, { "properties": "never" }]
  comma-spacing: 2
  comma-style: [2, "last"]
  key-spacing: 0 # [2, { "beforeColon": false, "afterColon": true, "align": "value" }]
  lines-around-comment:               [0, { "beforeBlockComment": true, "allowBlockStart": true, "allowBlockEnd": true, "allowObjectStart": true, "allowObjectEnd": true, "allowArrayStart": true, "allowArrayEnd": true }]
  max-len: [2, 120, 2]
  arrow-body-style: 0
  arrow-parens: 0
  arrow-spacing: [2, { "before": true, "after": true }]
  prefer-const: 2
  react/forbid-prop-types: [2, { "forbid": ["any", "array", "object"] }]
  react/prop-types: 2
  react/sort-prop-types: 2
  default-case: 2
  switch-colon-spacing: [2, {"after": true, "before": false}]
  no-useless-constructor: 2
