version: "3"

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - NODE_ENV=development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./server:/app/server/
    command: nodemon -L src/server.js
    restart: always
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    command: npm run start
    restart: always
  