version: '3'

services:
  dev:
    container_name: epf
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development