version: "3"
services:
  mongo1:
    image: mongo
    volumes:
    - mongo1data:/data/db
    ports:
    - "30001:27017"
    command: ["mongod", "--replSet", "epf_rs"]

  mongo2:
    image: mongo
    volumes:
    - mongo2data:/data/db
    ports:
    - "30002:27017"
    command: ["mongod", "--replSet", "epf_rs"]

  mongo3:
    image: mongo
    volumes:
    - mongo3data:/data/db
    ports:
    - "30003:27017"
    command: ["mongod", "--replSet", "epf_rs"]

  mongosetup:
    image: mongo
    volumes:
      - ./scripts:/scripts
    entrypoint: ["bash", "/scripts/mongoSetup.sh"]

  server:
    image: docker-snapshot.cernerrepos.net/rwcm/rwcm_epf_server_dev
    environment:
      - MONGO_URI=27017
      - PORT=5000
      - NODE_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./server:/app/server/
    command: nodemon -L server/server.js
    restart: always
    depends_on: 
      - mongosetup
  client:
    image: docker-snapshot.cernerrepos.net/rwcm/rwcm_epf_client_dev
    environment:
      - REACT_APP_PORT=3000
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    command: npm run start
    restart: always
    depends_on: 
      - server
volumes:
  mongo1data:
  mongo2data:
  mongo3data:
